language: bash
services: docker

env:
  - VERSION=jdk7
  - VERSION=jdk7 VARIANT=alpine
  - VERSION=jdk7 VARIANT=slim
  - VERSION=jre7
  - VERSION=jre7 VARIANT=alpine
  - VERSION=jre7 VARIANT=slim
  - VERSION=jdk8
  - VERSION=jdk8 VARIANT=alpine
  - VERSION=jdk8 VARIANT=slim
  - VERSION=jre8
  - VERSION=jre8 VARIANT=alpine
  - VERSION=jre8 VARIANT=slim
  - VERSION=jdk10
  - VERSION=jdk10 VARIANT=slim
  - VERSION=jre10
  - VERSION=jre10 VARIANT=slim
  - VERSION=jdk11
  - VERSION=jdk11 VARIANT=slim
  - VERSION=jre11
  - VERSION=jre11 VARIANT=slim

before_install:
  - env | sort
  - cd "${VERSION}${VARIANT:+-$VARIANT}"
  - image="gradle:${VERSION}${VARIANT:+-$VARIANT}"
  - docker rmi "${image}" || true
  - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
  - docker images --format "table {{.Repository}}:{{.Tag}}" | tail --lines=+2 | grep "openjdk" | xargs --no-run-if-empty --max-lines=1 docker pull

install:
  - docker build --tag "${image}" .

script:
  - cd ../test
  - ./run.sh "${image}" "4.10.2"
